from django.utils.translation import gettext as _

countries = (
    _("United States"),
    _("Afghanistan"),
    _("Albania"),
    _("Algeria"),
    _("American Samoa"),
    _("Andorra"),
    _("Angola"),
    _("Anguilla"),
    _("Antarctica"),
    _("Antigua And Barbuda"),
    _("Argentina"),
    _("Armenia"),
    _("Aruba"),
    _("Australia"),
    _("Austria"),
    _("Azerbaijan"),
    _("Bahamas"),
    _("Bahrain"),
    _("Bangladesh"),
    _("Barbados"),
    _("Belarus"),
    _("Belgium"),
    _("Belize"),
    _("Benin"),
    _("Bermuda"),
    _("Bhutan"),
    _("Bolivia"),
    _("Bosnia And Herzegowina"),
    _("Botswana"),
    _("Bouvet Island"),
    _("Brazil"),
    _("British Indian Ocean Territory"),
    _("Brunei Darussalam"),
    _("Bulgaria"),
    _("Burkina Faso"),
    _("Burundi"),
    _("Cambodia"),
    _("Cameroon"),
    _("Canada"),
    _("Cape Verde"),
    _("Cayman Islands"),
    _("Central African Republic"),
    _("Chad"),
    _("Chile"),
    _("China"),
    _("Christmas Island"),
    _("Cocos (Keeling) Islands"),
    _("Colombia"),
    _("Comoros"),
    _("Congo"),
    _("Congo, The Democratic Republic Of The"),
    _("Cook Islands"),
    _("Costa Rica"),
    _("Cote d'Ivoire"),
    _("Croatia"),
    _("Cuba"),
    _("Cyprus"),
    _("Czech Republic"),
    _("Denmark"),
    _("Djibouti"),
    _("Dominica"),
    _("Dominican Republic"),
    _("Ecuador"),
    _("Egypt"),
    _("El Salvador"),
    _("Equatorial Guinea"),
    _("Eritrea"),
    _("Estonia"),
    _("Ethiopia"),
    _("Falkland Islands"),
    _("Faroe Islands"),
    _("Fiji"),
    _("Finland"),
    _("France"),
    _("French Guiana"),
    _("French Polynesia"),
    _("French Southern Territories"),
    _("Gabon"),
    _("Gambia"),
    _("Georgia"),
    _("Germany"),
    _("Ghana"),
    _("Gibraltar"),
    _("Greece"),
    _("Greenland"),
    _("Grenada"),
    _("Guadeloupe"),
    _("Guam"),
    _("Guatemala"),
    _("Guernsey"),
    _("Guinea"),
    _("Guinea-bissau"),
    _("Guyana"),
    _("Haiti"),
    _("Heard And McDonald Islands"),
    _("Holy See"),
    _("Honduras"),
    _("Hong Kong"),
    _("Hungary"),
    _("Iceland"),
    _("India"),
    _("Indonesia"),
    _("Iran"),
    _("Iraq"),
    _("Ireland"),
    _("Isle of Man"),
    _("Israel"),
    _("Italy"),
    _("Jamaica"),
    _("Japan"),
    _("Jersey"),
    _("Jordan"),
    _("Kazakhstan"),
    _("Kenya"),
    _("Kiribati"),
    _("Korea, Democratic People's Republic Of"),
    _("Korea, Republic Of"),
    _("Kuwait"),
    _("Kyrgyzstan"),
    _("Laos"),
    _("Latvia"),
    _("Lebanon"),
    _("Lesotho"),
    _("Liberia"),
    _("Libya"),
    _("Liechtenstein"),
    _("Lithuania"),
    _("Luxembourg"),
    _("Macao"),
    _("Macedonia"),
    _("Madagascar"),
    _("Malawi"),
    _("Malaysia"),
    _("Maldives"),
    _("Mali"),
    _("Malta"),
    _("Marshall Islands"),
    _("Martinique"),
    _("Mauritania"),
    _("Mauritius"),
    _("Mayotte"),
    _("Mexico"),
    _("Micronesia"),
    _("Moldova, Republic Of"),
    _("Monaco"),
    _("Mongolia"),
    _("Montserrat"),
    _("Morocco"),
    _("Mozambique"),
    _("Myanmar"),
    _("amibia"),
    _("auru"),
    _("epal"),
    _("etherlands"),
    _("etherlands Antilles"),
    _("ew Caledonia"),
    _("ew Zealand"),
    _("icaragua"),
    _("iger"),
    _("igeria"),
    _("iue"),
    _("orfolk Island"),
    _("orthern Mariana Islands"),
    _("orway"),
    _("Oman"),
    _("Pakistan"),
    _("Palau"),
    _("Palestinian Territory"),
    _("Panama"),
    _("Papua ew Guinea"),
    _("Paraguay"),
    _("Peru"),
    _("Philippines"),
    _("Pitcairn"),
    _("Poland"),
    _("Portugal"),
    _("Puerto Rico"),
    _("Qatar"),
    _("Reunion"),
    _("Romania"),
    _("Russian Federation"),
    _("Rwanda"),
    _("Saint Kitts And evis"),
    _("Saint Lucia"),
    _("Saint Vincent And The Grenadines"),
    _("Samoa"),
    _("San Marino"),
    _("Sao Tome And Principe"),
    _("Saudi Arabia"),
    _("Senegal"),
    _("Serbia And Montenegro"),
    _("Seychelles"),
    _("Sierra Leone"),
    _("Singapore"),
    _("Slovakia"),
    _("Slovenia"),
    _("Solomon Islands"),
    _("Somalia"),
    _("South Africa"),
    _("South Georgia And The South Sandwich Islands"),
    _("Spain"),
    _("Sri Lanka"),
    _("St. Helena"),
    _("St. Pierre And Miquelon"),
    _("Sudan"),
    _("Suriname"),
    _("Svalbard And Jan Mayen Islands"),
    _("Swaziland"),
    _("Sweden"),
    _("Switzerland"),
    _("Syria"),
    _("Taiwan"),
    _("Tajikistan"),
    _("Tanzania, United Republic Of"),
    _("Thailand"),
    _("Timor-Leste"),
    _("Togo"),
    _("Tokelau"),
    _("Tonga"),
    _("Trinidad And Tobago"),
    _("Tunisia"),
    _("Turkey"),
    _("Turkmenistan"),
    _("Turks And Caicos Islands"),
    _("Tuvalu"),
    _("Uganda"),
    _("Ukraine"),
    _("United Arab Emirates"),
    _("United Kingdom"),
    _("United States Minor Outlying Islands"),
    _("Uruguay"),
    _("Uzbekistan"),
    _("Vanuatu"),
    _("Venezuela"),
    _("Viet am"),
    _("Virgin Islands, British"),
    _("Virgin Islands, U.S."),
    _("Wallis And Futuna Islands"),
    _("Western Sahara"),
    _("Yemen"),
    _("Zambia"),
    _("Zimbabwe"),
)
